//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------
using HZ.IDTSCore.Model;
using System.Collections.Generic;
using System.Threading.Tasks;
using SqlSugar;
using HZ.DbHelper;

namespace HZ.IDTSCore.Interfaces
{
    public partial class LogisticsOrderService : BaseService<tn_wms_logistics_order>, ILogisticsOrderService
    {

        public LogisticsOrderService(SessionInfo session) : base(session) { }
        #region CustomInterface 
        #endregion

    }
}
