//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------
using HZ.IDTSCore.Model;
using SqlSugar;
using System;
using HZ.CommonUtil.Model;
using SqlSugar.Extensions;
using HZ.DbHelper;

namespace HZ.IDTSCore.Interfaces
{
    public partial class OnePieceCodeService : BaseService<tn_wms_one_piece_code>, IOnePieceCodeService
    {
        public OnePieceCodeService(SessionInfo session) : base(session) { }
        public PagedInfo<tn_wms_one_piece_code> GetPages(PageParm parm)
        {
            string cn_s_from_buss = parm.Parms["cn_s_from_buss"].ObjToString();
            string cn_s_from_no = parm.Parms["cn_s_from_no"].ObjToString();
            string cn_s_production_batch = parm.Parms["cn_s_production_batch"].ObjToString();
            string cn_s_other_lotcode = parm.Parms["cn_s_other_lotcode"].ObjToString();
            string statyproduction = parm.Parms["statyproduction"].ObjToString();
            string endproduction = parm.Parms["endproduction"].ObjToString();
            string statyinstorage = parm.Parms["statyinstorage"].ObjToString();
            string endinstorage = parm.Parms["endinstorage"].ObjToString();

            return Db.Queryable<tn_wms_one_piece_code>()
            .WhereIF(!string.IsNullOrEmpty(cn_s_from_buss), (s => s.cn_s_from_buss.Contains(cn_s_from_buss)))
            .WhereIF(!string.IsNullOrEmpty(cn_s_from_no), (s => s.cn_s_from_no.Contains(cn_s_from_no)))
            .WhereIF(!string.IsNullOrEmpty(cn_s_production_batch), (s => s.cn_s_production_batch.Contains(cn_s_production_batch)))
            .WhereIF(!string.IsNullOrEmpty(cn_s_other_lotcode), (s => s.cn_s_other_lotcode.Contains(cn_s_other_lotcode)))
            .WhereIF(!string.IsNullOrEmpty(statyproduction)&& !string.IsNullOrEmpty(endproduction), s => s.cn_t_production> DateTime.Parse(statyproduction)&&s.cn_t_production< DateTime.Parse(endproduction))
            .WhereIF(!string.IsNullOrEmpty(statyinstorage) && !string.IsNullOrEmpty(endinstorage), s => s.cn_t_in_storage_date > DateTime.Parse(statyinstorage) && s.cn_t_production < DateTime.Parse(endinstorage))
            .ToPage(parm.PageIndex, parm.PageSize);
        }
    }
}
