//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;
using System.Collections.Generic;
using HZ.IDTSCore.Model.SerializeEntity;

namespace HZ.IDTSCore.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("SYS_USER")]
    public class SYS_USER
    {
          public SYS_USER()
          {
          }

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// <summary>
                      
           [SugarColumn(IsPrimaryKey=true)]
           public string Id {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// <summary>
                      
           public string UserCode {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// <summary>
                      
           public string Password {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// <summary>
                      
           public string UserName { get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 0
           /// <summary>
                      
           public bool Is_Disabled {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public DateTime? Create_Time {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string Remark {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// <summary>
                      
           public bool OneSession {get;set;}

           /// <summary>
           /// 手机ID，用于推送审核消息 -咸阳项目
           /// </summary>
           public string PhoneID { get; set; }

           public string TokenId { get; set; }

        public List<string> AuthorizeStock = new List<string>();

        public string SplitDbCode { get; set; }

        public List<SplitDb> SplitDbList = new List<SplitDb>();
    }
}