//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace HZ.IDTSCore.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("tn_wms_interface_def")]
    public class tn_wms_interface_def
    {
        /// <summary>
        /// 接口编码
        /// </summary>
        [SugarColumn(IsPrimaryKey =true)]
        public string cn_s_infcode { get; set; }

        /// <summary>
        /// 接口地址
        /// </summary>
        public string cn_s_url { get; set; }

        /// <summary>
        /// 请求类型
        /// </summary>
        public string cn_s_mode { get; set; }

        /// <summary>
        /// 请求数据类型
        /// </summary>
        public string cn_s_data_type { get; set; }

        /// <summary>
        /// 请求数据
        /// </summary>
        [SugarColumn(IsIgnore = true)]
        public string cn_s_data { get; set; }

        /// <summary>
        /// 接口描述
        /// </summary>
        public string cn_s_note { get; set; }

        /// <summary>
        /// 响应数据类型
        /// </summary>
        public string cn_s_result_type { get; set; }

        /// <summary>
        /// 响应标识
        /// </summary>
        public string cn_s_result_flag { get; set; }

        /// <summary>
        /// 成功标识
        /// </summary>
        public string cn_s_succ_value { get; set; }

        /// <summary>
        /// 错误信息标识
        /// </summary>
        public string cn_s_err_msg_flag { get; set; }

        /// <summary>
        /// 不重试编码，编码集合，逗号隔开
        /// </summary>
        public string cn_s_notry_codes { get; set; }
        /// <summary>
        /// 是否并行，默认串行
        /// </summary>
        public bool cn_b_parallel { get; set; }

        /// <summary>
        /// 认证方式
        /// </summary>
        public string cn_s_auth_type { get; set; }

        /// <summary>
        /// 用户名
        /// </summary>
        public string cn_s_usercode { get; set; }

        /// <summary>
        /// 密码
        /// </summary>
        public string cn_s_pwd { get; set; }

        /// <summary>
        /// 接口ip
        /// </summary>
        public string cn_s_ip { get; set; }

        /// <summary>
        /// 接口port
        /// </summary>
        public int? cn_n_port { get; set; }

        /// <summary>
        /// 接口名称
        /// </summary>
        public string cn_s_infname { get; set; }

        /// <summary>
        /// 第三方系统
        /// </summary>
        public string cn_s_other_sys { get; set; }

        /// <summary>
        /// 允许重试次数 0:不重试   N:重试次数  -1:永久重试
        /// </summary>
        public int cn_n_max_retry { get; set; }

        /// <summary>
        /// SOAP Header元素
        /// </summary>
        public string cn_s_header { get; set; }

        /// <summary>
        /// 密钥
        /// </summary>
        public string cn_s_jwttoken { get; set; }

        /// <summary>
        /// 实现类
        /// </summary>
        public string cn_s_instance { get; set; }




        [SugarColumn(IsIgnore = true)]
        public string cn_s_send_content { get; set; }

    }
}