//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------
using HZ.CommonUtil.Model;
using HZ.IDTSCore.Model;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace HZ.IDTSCore.Interfaces
{
    public partial interface IOnePieceCodeService : IBaseService<tn_wms_one_piece_code>
    {

        #region CustomInterface 

        public PagedInfo<tn_wms_one_piece_code> GetPages(PageParm parm);

        #endregion

    }
}
