//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace HZ.IDTSCore.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("tn_wms_view_table_conf")]
    public class tn_wms_view_table_conf
    {
        public tn_wms_view_table_conf()
        {
        }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_power_code { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_power_name { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_column_code { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_column_name { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public int? cn_n_width { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_align { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_method_name { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_input_type { get; set; }

        
        public string cn_s_dict_name { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public int cn_n_order { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_table { get; set; }

        
        public bool? cn_b_is_sort { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_link { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public bool cn_b_is_valid { get; set; }

        
        public bool cn_b_required { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public bool? cn_b_is_built_in { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_creator { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_creator_by { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public DateTime? cn_t_create { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_modify { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_modify_by { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public DateTime? cn_t_modify { get; set; }
        
        public bool cn_b_active { get; set; }
        
        public string cn_s_obj { get; set; }

        
        public int cn_n_max_length { get; set; }

        [SugarColumn(IsIgnore =true)]
        public bool cn_b_enabled { get; set; }
        
    }
}