//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;
using System.Collections.Generic;

namespace HZ.IDTSCore.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("tn_wms_view_table_def")]
    public class tn_wms_view_table_def
    {
        public tn_wms_view_table_def()
        {
        }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        [SugarColumn(IsPrimaryKey = true)]
        public string cn_s_power_code { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_power_name { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public bool? cn_b_is_edit { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_show_style { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_org_code { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_creator { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_creator_by { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public DateTime? cn_t_create { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_modify { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_modify_by { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public DateTime? cn_t_modify { get; set; }

        public string cn_s_guid { get; set; }
        public string cn_s_parent_guid { get; set; }

        public List<tn_wms_view_table_def> child = new List<tn_wms_view_table_def>();
    }
}