//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace HZ.IDTSCore.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("tn_wms_location")]
    public class tn_wms_location
    {
        public tn_wms_location()
        {
        }

        /// <summary>
        /// 描述 :  仓库号
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_stock_code { get; set; }

        /// <summary>
        /// 描述 :  仓库名称
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_stock_name { get; set; }


        /// <summary>
        /// 描述 :  巷道
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_roadway { get; set; }

        /// <summary>
        /// 描述 :  库区
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_area_code { get; set; }
        /// <summary>
        /// 描述 :  库区名
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_area_name { get; set; }

        /// <summary>
        /// 描述 :  锁定任务号
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_task_no { get; set; }

        /// <summary>
        /// 描述 :  排号
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_row { get; set; }
        /// <summary>
        /// 描述 :  列
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public int cn_n_col { get; set; }

        /// <summary>
        /// 描述 :  层
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public int cn_n_floor { get; set; }

        /// <summary>
        /// 描述 :  货位号
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        [SugarColumn(IsPrimaryKey = true)]
        public string cn_s_location_code { get; set; }
        public string cn_s_location_name { get; set; }

        /// <summary>
        /// 描述 :  货位状态
        /// 空值 : True
        /// 默认 : 
        /// <summary>

        public string cn_s_location_state { get; set; }

        /// <summary>
        /// 描述 :  使用状态
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_use_state { get; set; }

        /// <summary>
        /// 描述 :  变更前状态
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_bef_fault_state { get; set; }

        /// <summary>
        /// 描述 :  货位标识
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_location_flag { get; set; }

        /// <summary>
        /// 描述 :  控制属性
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_ctl_property { get; set; }

        /// <summary>
        /// 描述 :  最大重量
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public decimal cn_f_max_weight { get; set; }

        /// <summary>
        /// 描述 :  最大体积(长)
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public int? cn_f_max_long { get; set; }

        /// <summary>
        /// 描述 :  最大体积(宽)
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public int? cn_f_max_wide { get; set; }

        /// <summary>
        /// 描述 :  最大体积(高)
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public int? cn_f_max_high { get; set; }

        /// <summary>
        /// 描述 :  创建人
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_creator { get; set; }

        /// <summary>
        /// 描述 :  创建人名称
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_creator_by { get; set; }

        /// <summary>
        /// 描述 :  创建时间
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public DateTime? cn_t_create { get; set; }

        /// <summary>
        /// 描述 :  修改人
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_modify { get; set; }

        /// <summary>
        /// 描述 :  修改人名称
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_modify_by { get; set; }

        /// <summary>
        /// 描述 :  修改时间
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public DateTime? cn_t_modify { get; set; }

        
        public string cn_s_passageway { get; set; }

        //货架号
        public string cn_s_goods_shelves { get; set; }
        //货位序号
        public int cn_n_order { get; set; }
        //正反面
        public string cn_s_face { get; set; }
        /// <summary>
        /// 来源系统
        /// </summary>
        public string cn_s_source_sys { get; set; }
        public string cn_s_agv_bit{ get; set; }


        [SugarColumn(IsIgnore = true)]
        public int cn_n_weighting { get; set; }
        public int cn_n_depth { get; set; }
        public string cn_s_depth_flag { get; set; }

        /// <summary>
        /// 不加任务锁
        /// </summary>
        public bool cn_b_task_unlock { get; set; }

        /// <summary>
        /// 不加使用锁
        /// </summary>
        public bool cn_b_use_unlock { get; set; }
    }
}