//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace HZ.IDTSCore.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("tn_wms_one_piece_code")]
    public class tn_wms_one_piece_code
    {
          public tn_wms_one_piece_code()
          {
          }

           /// <summary>
           /// 描述 :  
           /// 空值 : False
           /// 默认 : 
           /// <summary>
                      
           [SugarColumn(IsPrimaryKey=true)]
           public string cn_s_serial_no { get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_stock_code {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_stock_name {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_owner {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_item_code {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_item_name {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_item_state {get;set;}

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
                   
           public string cn_s_item_class {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_model {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_unit {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_state {get;set;}




        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_from_buss { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_from_no { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public DateTime? cn_t_production { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public DateTime? cn_t_in_storage_date { get; set; }


        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_production_batch { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
        
        public string cn_s_other_lotcode { get; set; }

    }
}