//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace HZ.IDTSCore.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("tn_wms_owner")]
    public class tn_wms_owner
    {
        public readonly object cn_s_org_type;

        public tn_wms_owner()
          {
          }

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
           
        [SugarColumn(IsPrimaryKey = true)]
        public string cn_s_owner_code { get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_owner_name {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_org_code {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_org_name {get;set;}

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
                   
           public string cn_s_owner_type {get;set;}
        
           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
           
           public bool cn_b_is_used { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>
                   
           public bool? cn_b_is_default {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_creator {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_creator_by {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public DateTime? cn_t_create {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_modify {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_modify_by {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public DateTime? cn_t_modify {get;set;}

        public string cn_s_stock_code { get; set; }
        public string cn_s_stock_name { get; set; }
    }
}