//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace HZ.IDTSCore.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("tn_wms_logistics_order")]
    public class tn_wms_logistics_order
    {
          public tn_wms_logistics_order()
          {
          }

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_logistics_flag {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_logistics_name {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_logistics_code {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public bool? cn_b_electronic_sheet {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_op_no {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_status {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_trans_status {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_curr_address {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_f_exptype_code {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_f_exptype_name {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_start_province {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_start_city {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_start_area_county {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_start_township_street {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_start_address {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_sender_company {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_sender {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_sender_phone {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_end_province {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_end_city {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_end_area_county {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_end_township_street {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_end_address {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_receive_company {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_receive {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_receive_phone {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public DateTime? cn_t_exp_arrival_time {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public DateTime? cn_t_send_time {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public DateTime? cn_t_pick_up_time {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public DateTime? cn_t_sign_for_time {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public decimal cn_f_theory_weight {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public decimal cn_f_charging_weight {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public decimal cn_f_logistics_fee {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public int? cn_n_sub_logistics_num {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_sub_logistics_codes {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_refund_order {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public decimal cn_f_refund_fee {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public decimal cn_s_service_fee {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public decimal cn_s_uodoor_fee {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public decimal cn_s_ensure_fee {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_subscribe_return {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_signer {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_signer_phone {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_signfor_type {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_signfor_remark {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_signfor_packing {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_signfor_code {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_autograph_img_path {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public DateTime? cn_t_create {get;set;}

    }
}