//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace HZ.IDTSCore.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("tn_wms_rule_fix")]
    public class tn_wms_rule_fix
    {
          public tn_wms_rule_fix()
          {
          }

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_rule_name {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_rule_fix {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public int? cn_n_rule_lenth {get;set;}

           /// <summary>
           /// 描述 :  
           /// 空值 : True
           /// 默认 : 
           /// <summary>
                      
           public string cn_s_state {get;set;}

    }
}