//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
//     author MEIAM
// </auto-generated>
//------------------------------------------------------------------------------

using System.ComponentModel.DataAnnotations;
using System;
using System.Linq;
using System.Text;
using SqlSugar;


namespace HZ.IDTSCore.Model
{
    ///<summary>
    ///
    ///</summary>
    [SugarTable("tn_wms_item")]
    public class tn_wms_item
    {
        public tn_wms_item()
        {
        }


        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>


        private string _cn_s_item_code = "";
        [SugarColumn(IsPrimaryKey = true)]
        public string cn_s_item_code { get { return _cn_s_item_code; } set { _cn_s_item_code = value; } }

        public decimal cn_f_tw { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>

        public decimal cn_f_nw { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>

        public int? cn_n_volume_wide { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>

        public int? cn_n_volume_height { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>

        public int? cn_n_volume_unit { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>

        public decimal cn_f_min_packweight { get; set; }


        public bool cn_b_one_piece { get; set; }

        /// <summary>
        /// 描述 :  
        /// 空值 : True
        /// 默认 : 
        /// <summary>

        public int? cn_n_min_packqty { get; set; }

        public int cn_n_expiration_date { get; set; }

        public int? cn_n_maintain_cycle { get; set; }

        /// <summary>
        /// 标准价格
        /// </summary>
        public decimal cn_f_price { get; set; }


        private string _cn_s_maintain_unit = "";
        public string cn_s_maintain_unit { get { return _cn_s_maintain_unit; } set { _cn_s_maintain_unit = value; } }

        private string _cn_s_item_name = "";
        public string cn_s_item_name { get { return _cn_s_item_name; } set { _cn_s_item_name = value; } }
        private string _cn_s_brand = "";
        public string cn_s_brand { get { return _cn_s_brand; } set { _cn_s_brand = value; } }
        private string _cn_s_item_class = "";
        public string cn_s_item_class { get { return _cn_s_item_class; } set { _cn_s_item_class = value; } }
        private string _cn_s_model = "";
        public string cn_s_model { get { return _cn_s_model; } set { _cn_s_model = value; } }
        private string _cn_s_figure_no = "";
        public string cn_s_figure_no { get { return _cn_s_figure_no; } set { _cn_s_figure_no = value; } }
        private string _cn_s_color = "";
        public string cn_s_color { get { return _cn_s_color; } set { _cn_s_color = value; } }
        private string _cn_s_season = "";
        public string cn_s_season { get { return _cn_s_season; } set { _cn_s_season = value; } }
        private string _cn_s_unit = "";
        public string cn_s_unit { get { return _cn_s_unit; } set { _cn_s_unit = value; } }
        private string _cn_s_weight_unit = "";
        public string cn_s_weight_unit { get { return _cn_s_weight_unit; } set { _cn_s_weight_unit = value; } }
        private string _cn_s_volume_long = "";
        public string cn_s_volume_long { get { return _cn_s_volume_long; } set { _cn_s_volume_long = value; } }
        private string _cn_s_pick_type = "";
        public string cn_s_pick_type { get { return _cn_s_pick_type; } set { _cn_s_pick_type = value; } }
        private string _cn_s_sale_type = "";
        public string cn_s_sale_type { get { return _cn_s_sale_type; } set { _cn_s_sale_type = value; } }
        //public string cn_s_owner_name { get; set; }

        private string _cn_s_ext1 = "";
        public string cn_s_ext1
        {
            get { return _cn_s_ext1; }
            set { _cn_s_ext1 = value; }
        }
        private string _cn_s_ext2 = "";
        public string cn_s_ext2 {
            get { return _cn_s_ext2; }
            set { _cn_s_ext2 = value; }
        }
        private string _cn_s_ext3 = "";
        public string cn_s_ext3 {
            get { return _cn_s_ext3; }
            set { _cn_s_ext3 = value; }
        }
        private string _cn_s_ext4 = "";
        public string cn_s_ext4 {
            get { return _cn_s_ext4; }
            set { _cn_s_ext4 = value; }
        }
        private string _cn_s_ext5 = "";
        public string cn_s_ext5 {
            get { return _cn_s_ext5; }
            set { _cn_s_ext5 = value; }
        }
        private string _cn_s_ext6 = "";
        public string cn_s_ext6 {
            get { return _cn_s_ext6; }
            set { _cn_s_ext6 = value; }
        }
        private string _cn_s_ext7 = "";
        public string cn_s_ext7 {
            get { return _cn_s_ext7; }
            set { _cn_s_ext7 = value; }
        }
        private string _cn_s_ext8 = "";
        public string cn_s_ext8 {
            get { return _cn_s_ext8; }
            set { _cn_s_ext8 = value; }
        }
        private string _cn_s_ext9 = "";
        public string cn_s_ext9
        {
            get { return _cn_s_ext9; }
            set { _cn_s_ext9 = value; }
        }
        private string _cn_s_ext10 = "";
        public string cn_s_ext10 {
            get { return _cn_s_ext10; }
            set { _cn_s_ext10 = value; }
        }
        private string _cn_s_ext11 = "";
        public string cn_s_ext11 {
            get { return _cn_s_ext11; }
            set { _cn_s_ext11 = value; }
        }
        private string _cn_s_ext12 = "";
        public string cn_s_ext12 {
            get { return _cn_s_ext12; }
            set { _cn_s_ext12 = value; }
        }
        private string _cn_s_ext13 = "";
        public string cn_s_ext13 {
            get { return _cn_s_ext13; }
            set { _cn_s_ext13 = value; }
        }
        private string _cn_s_ext14 = "";
        public string cn_s_ext14 {
            get { return _cn_s_ext14; }
            set { _cn_s_ext14 = value; }
        }
        private string _cn_s_ext15 = "";
        public string cn_s_ext15 {
            get { return _cn_s_ext15; }
            set { _cn_s_ext15 = value; }
        }
        //private string _cn_s_ext16 = "";
        //public string cn_s_ext16 {
        //    get { return _cn_s_ext16; }
        //    set { _cn_s_ext16 = value; }
        //}
        //private string _cn_s_ext17 = "";
        //public string cn_s_ext17 {
        //    get { return _cn_s_ext17; }
        //    set { _cn_s_ext17 = value; }
        //}
        //private string _cn_s_ext18 = "";
        //public string cn_s_ext18 {
        //    get { return _cn_s_ext18; }
        //    set { _cn_s_ext18 = value; }
        //}
        //private string _cn_s_ext19 = "";
        //public string cn_s_ext19 {
        //    get { return _cn_s_ext19; }
        //    set { _cn_s_ext19 = value; }
        //}
        //private string _cn_s_ext20 = "";
        //public string cn_s_ext20
        //{
        //    get { return _cn_s_ext20; }
        //    set { _cn_s_ext20 = value; }
        //}


        /// <summary>
        /// 默认的包装数量
        /// </summary>
        [SugarColumn(IsIgnore = true)]
        public int defaultPackageQty { get; set; }
        public string cn_s_minor_type { get; set; }
        public string cn_s_major_type { get; set; }


        /// <summary>
        /// 华为物料代码 -2023年1月31日新增
        /// </summary>
        public string cn_s_mfrpn { get; set; }

        /// <summary>
        /// 华为物料英文描述 -2023年1月31日新增
        /// </summary>
        public string cn_s_normt { get; set; }

        /// <summary>
        /// 物料保质期（天） -2023年1月31日新增
        /// </summary>
        public decimal cn_f_maxlz { get; set; }

        /// <summary>
        /// 质检提前期（天） -2023年1月31日新增
        /// </summary>
        public decimal cn_f_raube { get; set; }
    }
}